name: build-windows-exe

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install build tools
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Build with PyInstaller (spec)
        shell: pwsh
        run: pyinstaller app.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuickPortableDiskTool-windows
          path: dist/QuickPortableDiskTool.exe
          if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: QuickPortableDiskTool-windows
          path: dist

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/QuickPortableDiskTool.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

